
fn throwFunc()
{
	throw "catch";
}

fn main()
{
	try{
		return throwFunc();
	}catch(ex){
		return ex;
	}
}