
fn main()
{
	try{
		throw "error";
	}catch(ex){
		return "catch";
	}
}