
fn main()
{
	let str = undefined;
	
	try{

		try{
			throw "test exception";
		} catch(ex){
			throw ex;
		}

	}catch(ex){
		str = ex;
	}

	return str;
}